name: pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache npm dependencies
        uses: actions/cache@v3.0.4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: ${{ runner.OS }}-npm-cache
      - name: Install npm dependencies
        run: npm install
      - name: Add .env
        run: echo ${{ secrets.VITE_SHAZAM_CORE_RAPID_API_KEY }} > .env
      - name: Build project
        run: npm run build
      - name: Rename assets
        run: sed -i 's/\/assets/.\/assets/' dist/index.html && sed -i 's/\/assets/.\/assets/' dist/assets/index.*.js
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
